image: python:3.9

cache:
  paths:
    - ~/.cache/pip/

before_script:
  - python -V

stages:
  - test

test:
  stage: test
  script:
    - pip install -r requirements.txt
    - python manage.py migrate
    - python manage.py collectstatic --noinput
    - python manage.py test
