baseURL = "https://marketplace-fr.herokuapp.com/blog/"
languageCode = "fr-fr"
title = "Blog - Marketplace"
archetypeDir = "blog/archetypes"
contentDir = "blog/content"
data = "blog/data"
layoutDir = "blog/layouts"
staticDir = "blog/static"
themesDir = "blog/themes"
publishDir = "blog_out"
theme = "tale"
[Params]
[Author]
    name = "Staff"
