baseURL = "https://marketplace-fr.herokuapp.com/blog/"
languageCode = "fr-fr"
title = "Blog - Marketplace"
archetypeDir = "archetypes"
contentDir = "content"
data = "data"
layoutDir = "layouts"
staticDir = "static"
themesDir = "themes"
publishDir = "blog_out"
theme = "tale"
